# Generated by Django 2.2.2 on 2019-06-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image_url', models.CharField(default='', max_length=512)),
                ('status_field', models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('Available', 'Available'), ('Out of Stock', 'Unavailable')], default='', help_text='Shell availability', max_length=25)),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default='00.00', max_digits=4)),
                ('sku', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=50)),
                ('postal_code', models.DecimalField(decimal_places=0, default='', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('shipping_address', models.ForeignKey(on_delete='CASCADE', related_name='User', to='loveStore_app.Shipping_address')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='Order', to='loveStore_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default='')),
                ('order', models.ForeignKey(on_delete='SET_NULL', related_name='Item', to='loveStore_app.Order')),
                ('shell', models.ForeignKey(on_delete='CASCADE', related_name='Item', to='loveStore_app.Shell')),
            ],
        ),
    ]
