# Generated by Django 2.2.2 on 2019-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loveStore_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shell',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default='00', max_digits=4),
        ),
    ]
